name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ci test
        run: npm ci
      - name: build
        run: npm run build --if-present
      - name: test
        run: npm test
