name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ci
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
      - name: Push result to Testspace server
        run: testspace ./junit.xml
        if: always()
